spring:
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: off
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace